all:
	g++ IDMap.cpp heightMap.cpp main.cpp particleSystem.cpp -o main -lm -I ../include/ `pkg-config --cflags --libs opencv` 
	# g++ normalMap.cpp -o normalMap -lm -I ../include/ `pkg-config --cflags --libs opencv` 